import "./globals.css";
import NavLogo from "./ui/NavLogo";
import NavBar from "./ui/NavBar";
import type { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";

const robotoMono = Roboto_Mono({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body className={robotoMono.className}>{children}</body>
    </html>
  );
};

export default RootLayout;
